export const APP_COPY = Object.freeze({
  en: Object.freeze({
    languageButton: "中文",
    titles: {
      monitor: "Live Reminder",
      channels: "Channels",
      inbox: "Inbox",
      activity: "Activity",
      settings: "Settings",
    },
    nav: {
      monitor: "Monitor",
      channels: "Channels",
      inbox: "Inbox",
      activity: "Activity",
      settings: "Settings",
    },
    brandAlt: "Live Reminder",
    monitorList: "Monitored channels",
    monitorHint: "Choose the sources you want this self-hosted instance to monitor.",
    noMonitoredTitle: "No monitored channels",
    noMonitoredDetail: "Open Channels and enable at least one source.",
    allChannels: "All channels",
    channelsHint: "Each channel has an independent monitoring switch.",
    channelCount: (count) => `${count} ${count === 1 ? "channel" : "channels"}`,
    sourceAccount: (sourceId) => `Source ID: ${sourceId}`,
    live: "Live",
    offline: "Offline",
    unknown: "Unknown",
    monitorAria: (name) => `Monitor ${name}`,
    avatarAlt: (name) => `${name} avatar`,
    notificationSummary: "Confirmed live events are handed to the configured delivery adapter.",
    reminderEngine: "Reminder engine",
    engineDetail: "Creates one delivery record for each eligible recipient.",
    enabled: "Enabled",
    disabled: "Disabled",
    deliveryEvidence: "Delivery evidence",
    acceptedBoundary: "Accepted means the configured delivery adapter accepted the request. It does not confirm that a handset notification was displayed.",
    localInbox: "Local inbox",
    itemCount: (count) => `${count} ${count === 1 ? "item" : "items"}`,
    adapterLabel: (adapter) => `Adapter: ${adapter}`,
    adapterAccepted: "Accepted",
    all: "All",
    liveStarted: "Live started",
    liveEnded: "Live ended",
    diagnostics: "Diagnostics",
    deliveryAdapter: "Delivery adapter",
    localInboxAdapter: "Local inbox · development default",
    ready: "Ready",
    evidenceBoundary: "Evidence boundary",
  }),
  zh: Object.freeze({
    languageButton: "EN",
    titles: {
      monitor: "直播提醒",
      channels: "频道",
      inbox: "收件箱",
      activity: "活动",
      settings: "设置",
    },
    nav: {
      monitor: "监控",
      channels: "频道",
      inbox: "收件箱",
      activity: "活动",
      settings: "设置",
    },
    brandAlt: "直播提醒",
    monitorList: "已监控频道",
    monitorHint: "选择这个自托管实例需要监控的数据源。",
    noMonitoredTitle: "尚未监控频道",
    noMonitoredDetail: "请打开“频道”，并至少启用一个数据源。",
    allChannels: "全部频道",
    channelsHint: "每个频道都有独立的监控开关。",
    channelCount: (count) => `${count}个频道`,
    sourceAccount: (sourceId) => `数据源 ID：${sourceId}`,
    live: "直播中",
    offline: "未开播",
    unknown: "未知",
    monitorAria: (name) => `监控${name}`,
    avatarAlt: (name) => `${name}头像`,
    notificationSummary: "确认开播事件后，系统会将提醒交给已配置的发送适配器。",
    reminderEngine: "提醒引擎",
    engineDetail: "为每位符合条件的接收者创建一条发送记录。",
    enabled: "已启用",
    disabled: "已停用",
    deliveryEvidence: "发送证据",
    acceptedBoundary: "已接受仅表示发送适配器已接受请求，不代表手机已经显示通知。",
    localInbox: "本地收件箱",
    itemCount: (count) => `${count}项`,
    adapterLabel: (adapter) => `适配器：${adapter}`,
    adapterAccepted: "适配器已接受",
    all: "全部",
    liveStarted: "开始直播",
    liveEnded: "结束直播",
    diagnostics: "诊断",
    deliveryAdapter: "发送适配器",
    localInboxAdapter: "本地收件箱 · 开发默认项",
    ready: "就绪",
    evidenceBoundary: "证据边界",
  }),
});

export function getAppCopy(language) {
  return APP_COPY[language] || APP_COPY.en;
}
